version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - ./.postgres_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=levlog
      - POSTGRES_USER=levlog
      - POSTGRES_PASSWORD=levlog
    ports:
      - "5432:5432"
    restart: unless-stopped
