# Generated by Django 3.2.6 on 2021-08-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
