# Generated by Django 3.2.6 on 2021-08-08 20:15

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=stdimage.models.StdImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
