# Generated by Django 3.2.6 on 2021-08-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image_svg',
            field=models.FileField(null=True, upload_to='category_images/', verbose_name='image'),
        ),
    ]
