# Generated by Django 3.2.6 on 2022-04-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.TextField(default='', verbose_name='keywords'),
        ),
    ]
