# Generated by Django 3.2.6 on 2021-08-08 20:29

from django.db import migrations
import stdimage.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=tinymce.models.HTMLField(null=True, verbose_name='short'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=stdimage.models.StdImageField(null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='preview'),
        ),
    ]
