# Generated by Django 3.2.6 on 2021-08-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210808_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emoji_description',
            field=models.CharField(default='', max_length=10, verbose_name='emoji'),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=1, verbose_name='rating'),
        ),
    ]
