# Generated by Django 3.2.6 on 2021-08-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210808_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='emoji_description',
            field=models.CharField(max_length=10, null=True, verbose_name='emoji'),
        ),
    ]
